main/main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
import main.views
import newsletter.views
import diet.views
import workout.views

app_name = "main"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main.views.index, name='index'),
    path('news/', main.views.newspage, name='newspage'),
    path('diet/', main.views.dietpage, name='dietpage'),
    path('workout/', main.views.workoutpage, name='workoutpage'),
    path('user/', include('user.urls')),
    path('workout/routine1',main.views.routine1, name='routine1'),
    path('workout/routine2',main.views.routine2, name='routine2'),
    path('workout/routine3',main.views.routine3, name='routine3'),
    path('workout/routine4',main.views.routine4, name='routine4'),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

main/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('create_account/', views.user_create, name='user_create')
]

main/diet/models.py
from django.db import models

# Create your models here.

main/newsletter/models.py
from django.db import models

class NewsData(models.Model): 
    title = models.CharField(max_length=300) 
    url = models.URLField() 
    specific_id = models.CharField(max_length=15)

main/user/models.py
from django.db import models

# Create your models here.

main/workout/models.py
from django.db import models

# Create your models here.

main/diet/views.py
from django.shortcuts import render
from main import *

# Create your views here.

def dietpage(request):
    return render(request,'diet.html')

main/main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')
    
def workoutpage(request):
    return render(request, 'workout.html')

def dietpage(request):
    return render(request,'diet.html')

def newspage(request):
    return render(request, 'template.html')

def routine1(request):
    return render(request, 'routine1.html')
def routine2(request):
    return render(request, 'routine2.html')
def routine3(request):
    return render(request, 'routine3.html')
def routine4(request):
    return render(request, 'routine4.html')

main/newsletter/views.py
# from django.shortcuts import render

# def newspage(request):
#     return render(request, 'template.html')

# # 크롤링 파트
# import os 
# from urllib.parse import urlparse 
# import requests 
# from bs4 import BeautifulSoup 
# os.environ.setdefault('DJANGO_SETTINGS_MODULE', "main.settings") 
# import django 
# django.setup()
# from newsletter.models import NewsData
# #pip install bs4 필요

# def health_news(): 
#     headers = {"User_Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.52 Whale/3.12.129.29 Safari/537.36"}
#     result = [] 
#     url = 'https://news.naver.com/main/list.naver?mode=LS2D&mid=shm&sid1=103&sid2=241' 
#     req = requests.get(url, headers=headers) 
#     html = req.text 
#     status = req.status_code
#     can_run = req.ok
#     soup = BeautifulSoup(html, 'html.parser') 
#     web_page_url_root = "https://news.naver.com/" 
#     news_list = soup.select( 
#         'main_content > div.list_body.newsflash_body > ul.type06_headline > li:nth-child(1) > dl > dt:nth-child(2) > a'    
#     )
#     global title_list, url_list
#     result_list = []
#     url_list = []
#     for news in news_list:
#         i = 0
#         result_list[i] = news.text
#         result_list[i+10] = news.get('href')
#         i += 1
#         if i==10: break
#     return result_list
# if __name__ == '__main__':
#     health_news()
# print(health_news()[0])

main/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login 
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.http import require_POST
from main import *
# Create your views here.

def user_create(request) :
    if request.method== "POST" :
        form = UserCreationForm(request.POST)
        if form.is_valid() :
            user = form.save()
            auth_login(request, user)
            return redirect('main:views:index')
    else : # 회원가입 페이지 첫 접근
        form = UserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'signup.html', context)

def user_login(request) : 
    if request.user.is_authenticated :
        return redirect('main:index')
    if request.method=='POST' :
        form = AuthenticationForm(request, data = request.POST) 
        if form.is_valid() :
            auth_login(request, form.get_user())
            return redirect('main:index') # 로그인 성공시 메인페이지 이동
    else :
        form = AuthenticationForm()

    context = {
        'form' : form,
    }
    return render(request, 'login.html', context)

@require_POST
def user_logout(request) :
    auth_logout(request)
    return redirect('main:index')

main/workout/views.py
from django.shortcuts import render
from main import *

# Create your views here.

def workoutpage(request):
    return render(request, 'workout.html')

main/main/templates/Carousel.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="image/running.jpg" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h1> Exmaple Headline </h1>
                <p>I believe we are here on the planet Earth to live, grow up and do what we can to make this world a better place for all people to enjoy freedom. -- Rosa Parks</p>

              </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="image/muscle.jpg" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <h1> Exmaple Headline </h1>
                <p>I believe we are here on the planet Earth to live, grow up and do what we can to make this world a better place for all people to enjoy freedom. -- Rosa Parks</p>

              </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="image/blackgym.jpg" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h1> Exmaple Headline </h1>
                <p>I believe we are here on the planet Earth to live, grow up and do what we can to make this world a better place for all people to enjoy freedom. -- Rosa Parks</p>

              </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/main/templates/login.html
{% extends 'original.html' %}

{% block content %}
  <h1> 로그인 </h1>
  <form action="{% url 'user:user_login' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="로그인" />
</form>
{{request.user}}
{% endblock content %}

main/main/templates/routine1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Healthskku</title>
    <link rel = "stylesheet" href = "../static/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <!-- nav -->
    <nav class = "nav navbar navbar-expand-lg navbar-dark bg-dark py-3 fixed-top">
        <div class = "container">
            <a href="../.." class="navbar-brand">Healthskku  </a>
            <div class="collapse navbar-collapse">
                <ul class="navbar nav ms-auto ">
                    <li class = "nav-item">
                        <a href = "../../workout" class = "nav-link">Work out</a>
                    </li>
                    <li class = "nav-item">
                        <a href = "../../diet" class = "nav-link">Diet</a>
                    </li>
                    <li class = "nav-item">
                        <a href = "../../news" class = "nav-link">News</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Body Section-->
    <section id = "Body" calss = "p-5 bg-light">
        <div class="container">
            <div class="row align-items-center justify-content-between mt-5">
                <div class="col-md p-5">
                    <iframe width="660" height="375" src="https://www.youtube.com/embed/ml6cT4AZdqI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>    
                </div>
                <div class="col-md p-5">
                    <img src = "../static/image/body.jpg" class="rounded mx-auto d-block"  height="375">
                </div>
            </div>
        </div>

    </section>

    <!-- Effect Section-->
    <section id = "Effect" class = "p-5 bg-dark text-light">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md p-5 pt-0">
                    <h2>Benefits of Cardio</h2>
                    <br>
                    <p class="lead">If your main goal is to lose weight, cardio training lowers body fat. </p>
                    <p class="lead">Cardio helps burn a lot of calories, speeds up our metabolism and improves our body mass index (BMI). 
                        Performing cardio exercises regularly will help us maintain our ideal weight.</p>
                    
                </div>
                <div class="col-md">
                    <img src="../static/image/muscle.jpg" class="img-fluid">
                </div>
            </div>
        </div>
    </section>

    <!-- Routines Section-->
    <section id="Routines" class="p-5 bg-light">
        <div class="container">
            <h2 class="text-center text-dark">Our Routines</h2>
            <p class="lead text-center text-dark mb-5">
                I believe we are here on the planet Earth to live, grow up and do what we can to make this world a better place for all people to enjoy freedom. -- Rosa Parks 
            </p>
            <div class="row g-4">
                <div class="col-md-6 col-lg-3">
                    <div class="card bg-light" style = "border: solid gray">
                        <div class="card-body text-center">
                            <img src="https://image.freepik.com/free-vector/pilates-concept-illustration_114360-1111.jpg" class = "rounded-circle mb-3" style = "width: 128px; height: 128px"> 
                            <h3 class = "card-text">Cardio: 1</h3>
                            <p class="card-text"><h5>Burn your Fat</h5>Time: 30 mins <br> Pushup, Plank, Runge<br><br> “If you don’t make time for exercise, you’ll probably have to make time for illness.”</p>
                            <a href="../workout/routine1" class="btn btn-dark mt-3">
                                <strong>Go Work out</strong>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="card bg-light" style = "border: solid gray">
                        <div class="card-body text-center">
                            <img src="https://image.freepik.com/free-vector/pilates-concept-illustration_114360-1111.jpg" class = "rounded-circle mb-3" style = "width: 128px; height: 128px">
                            <h3 class = "card-text">Cardio: 2</h3>
                            <p class="card-text"><h5>Burn your Fat</h5>Time: 20 mins <br> Jumping Jack, Shoulder Tap<br><br>
                                 Warning: <br>This is much harder than Cardio: 1<br>
                                 You need to warm up very well</p>
                            <a href="../workout/routine2" class="btn btn-dark mt-3">
                                <strong>Go Work out</strong>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="card bg-light" style = "border: solid gray">
                        <div class="card-body text-center">
                            <img src="https://image.freepik.com/free-vector/brawny-caucasian-arm_1284-13546.jpg" class = "rounded-circle mb-3" style = "width: 128px; height: 128px">
                            <h3 class = "card-text">UPPER Bound</h3>
                            <p class="card-text"><h5>Burn your UPPER Bound</h5>Time: 20 mins <br> 
                                Arnold Press, Curl<br><br> 
                                Do you want to be in a good shape? <br>
                                You must try this</p>
                            <a href="../workout/routine3" class="btn btn-dark mt-3">
                                <strong>Go Work out</strong>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="card bg-light" style = "border: solid gray">
                        <div class="card-body text-center">
                            <img src="https://img.pikbest.com/png-images/qianku/half-squat-girl-fitness-exercise-leg-muscles_2063233.png!bw700" class = "rounded-circle mb-3" style = "width: 128px; height: 128px">
                            <h3 class = "card-text">Lower Bound</h3>
                            <p class="card-text"><h5>Burn your Lower Bound</h5>Time: 20 mins <br> 
                                Squat, Runge<br><br>
                                Lower Bound Exercise is the most important exercise<br>
                                Let's get it</p>
                            <a href="../workout/routine4" class="btn btn-dark mt-3">
                                <strong>Go Work out</strong>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-dark text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Team 12 Home Training</span>
        </div>
      
        <!-- Right -->
        </section>
        <!-- Section: Social media -->
    
        <!-- Section: Links  -->
        <section class="">
        <div class="container text-center text-md-start text-light mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold mb-4">
                    OSSP TEAM 12
                </h6>
                <p>
                    <strong>provided by:</strong> 
                </p>
                <p>Cheolseok, <br>Janghyun, <br>Junha
                </p>                                    
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                Products
                </h6>
                <p>
                <a href="#!" class="text-reset">Angular</a>
                </p>
                <p>
                <a href="#!" class="text-reset">React</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Vue</a>
                </p>

            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                Useful links
                </h6>
                <p>
                    <a href="https://brunch.co.kr/keyword/%EA%B1%B4%EA%B0%95%C2%B7%EC%9A%B4%EB%8F%99?q=g" class="text-reset">
                        Health
                    </a>
                </p>
                <p>
                    <a href="http://www.heodak.com/?NaPm=ct%3Dkvysy86y%7Cci%3Dcheckout%7Ctr%3Dds%7Ctrx%3D%7Chk%3D0702859f5d0a76f8573e461193d2cef935bf1c4f" class="text-reset">
                        Diet Food
                    </a>
                </p>
                <p>
                    <!-- Source 정리 -->
                    <a href="#!" class="text-reset">Source</a>
                </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                    Contact
                </h6>
                <p>SKKU, SEOUL, KOREA</p>
                <p>Cheol-Will/OSS_TEAM12</p>
                <p>+ 01 234 567 88</p>
            </div>
            <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
        </section>
        <!-- Section: Links  -->
    
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2021 Copyright:
        <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>